name: efficient_sdk
description: efficient的SDK插件
version: 0.0.3

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dart_des: ^1.0.2
  convert: ^3.0.2
  date_format: ^2.0.6
  qr_flutter: ^4.0.0
  web_socket_channel: ^2.2.0
  plugin_platform_interface: ^2.1.2
  lpinyin: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sr.efficient_sdk
        pluginClass: EfficientSdkPlugin
      ios:
        pluginClass: EfficientSdkPlugin
      windows:
        pluginClass: EfficientSdkPluginCApi
